### ISSUE TITLE
Klipper on MK3S

### ISSUE THREAD

**Issue by rkolbi** [PrusaOwners/prusaowners#68]
I cannot get the MK3S to successfully load the Klipper.elf.hax firmware. I have built it / followed the instructions here as well as the Klipper site, the firmware seems to be properly built by the RPI, I disconnect the RPI from AMA0, at USB cable, and flash the firmware but it just hangs. On hard reboot (off/on) the LCD screen just stays frozen on the initial Prusa screen.
I have tried making the firmware on Ubuntu and then flashing it over but the same thing happens. I also tried to use prusaslicer to send the firmware to the printer with the same result, but oddly enough verification goes to 101%. In all these instances and attempts, no error messages are displayed.
The printer is resolved by reflashing the marlin firmware via prusaslicer.

It would seem as if the printer control board is locked somehow to not allow such firmware. It seems odd because I am using a self-modified version of 3.9.0 and that is no problem at all.

Any help or insight would be greatly appreciated.

**Comment by Joseph-DiGiovanni** [comment]
Why was this closed? I'm having the same issue. Did you resolve it?

**Comment by Joseph-DiGiovanni** [comment]
Found the solution: You need to build the klipper printer firmware with UART1, its in the "Extra low level options" of makeconfig. It defaults to UART0 which is the USB B port.

https://github.com/Klipper3d/klipper/issues/721#issuecomment-426127384
